# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-27 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchpage', '0002_article_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='display',
        ),
    ]
